{
    "name": "Theme Flavor Enterprise — Premium Backend Theme",
    "version": "19.0.1.0.0",
    "category": "Tools",
    "summary": "Premium backend theme with 3 presets, dark mode, persistent sidebar, sticky headers, RTL, Google Fonts, zoom, bookmarks, custom login, and more",
    "description": "",
    "author": "Elata79",
    "website": "mailto:ziadelata@gmail.com",
    "license": "OPL-1",
    "price": 39.99,
    "currency": "USD",
    "depends": ["base_setup", "web", "mail"],
    "data": [
        "security/ir.model.access.csv",
        "views/res_config_settings_views.xml",
        "views/web_layout.xml",
        "views/login_template.xml",
        "data/default_config.xml",
    ],
    "assets": {
        "web._assets_primary_variables": [
            ("after", "web/static/src/scss/primary_variables.scss",
             "flavor_theme_enterprise/static/src/scss/primary_variables.scss"),
        ],
        "web.assets_backend": [
            "flavor_theme_enterprise/static/src/scss/variables.scss",
            "flavor_theme_enterprise/static/src/scss/sidebar.scss",
            "flavor_theme_enterprise/static/src/scss/topbar.scss",
            "flavor_theme_enterprise/static/src/scss/dashboard.scss",
            "flavor_theme_enterprise/static/src/scss/list_view.scss",
            "flavor_theme_enterprise/static/src/scss/form_view.scss",
            "flavor_theme_enterprise/static/src/scss/dark_mode.scss",
            "flavor_theme_enterprise/static/src/scss/utilities.scss",
            "flavor_theme_enterprise/static/src/scss/overrides.scss",
            "flavor_theme_enterprise/static/src/scss/sticky_headers.scss",
            "flavor_theme_enterprise/static/src/scss/rtl.scss",
            "flavor_theme_enterprise/static/src/scss/breadcrumbs.scss",
            "flavor_theme_enterprise/static/src/scss/density.scss",
            "flavor_theme_enterprise/static/src/scss/loader.scss",
            "flavor_theme_enterprise/static/src/scss/command_palette.scss",
            "flavor_theme_enterprise/static/src/js/theme_service.js",
            "flavor_theme_enterprise/static/src/js/sidebar.js",
            "flavor_theme_enterprise/static/src/js/command_palette.js",
            "flavor_theme_enterprise/static/src/js/dark_mode_toggle.js",
            "flavor_theme_enterprise/static/src/xml/templates.xml",
        ],
        "web.assets_frontend": [
            "flavor_theme_enterprise/static/src/scss/login.scss",
        ],
    },
    "images": [
        "static/description/banner.png",
        "static/description/preset_indigo.png",
        "static/description/preset_emerald.png",
        "static/description/preset_sand.png",
        "static/description/feat_search_popup.png",
        "static/description/feat_bookmarks.png",
        "static/description/feat_login_default.png",
        "static/description/feat_sticky.png",
        "static/description/feat_settings1.png",
    ],
    "application": True,
    "installable": True,
    "auto_install": False,
    "live_test_url": "",
}
